import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from './components/Header'
import Dishes from './components/Dishes'
import AddDish from './components/AddDish'
import { useState } from 'react'
import { useSession, signIn, signOut, getSession } from "next-auth/react"
import { redirect } from 'next/dist/server/api-utils'
import Cart from './components/Cart'
import AdminDish from './components/AdminDish'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {data:session} = useSession()
  return (
    <>
      <Head>
        <title>Appetite.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="/your-path-to-uicons/css/uicons-rounded-regular.css" rel="stylesheet" />
        <link href="/your-path-to-uicons/css/uicons-rounded-bold.css" rel="stylesheet" />
        <link href="/your-path-to-uicons/css/uicons-rounded-solid.css" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header session={session}/>
        {Dishes({ session })}
       <Footer/>
      </main>
    </>
  )
}

export async function getServerSideProps({req}){
  const session = await getSession({req})

  if(!session){
    return{
      redirect: {
        destination: '/login',
        permanent: false
      }
    }
  }

  return{
    props: { session }
  }
}
